### PR TITLE
Track all public method calls within callback

### PR DESCRIPTION
**Pull request by ghost**
This will allow for expectations about various method calls during execution
## Usage

``` ruby
describe Jackal::Foo do

  before do
    @runner = run_setup(:foo)
    @method_calls = track_method_calls(Jackal::Foo)
  end
  after { @runner.terminate }

  let(:actor) { Carnivore::Supervisor.supervisor[:foo] }

  it 'executes with valid payload' do
    payload = Jackal::Utils.new_payload(:test, {})
    result = transmit_and_wait(actor, payload)

    @method_calls.must_include(:execute)
  end

end
```

### CODE REVIEW

**Comment by ghost** [comment]
Let me know if / when this gets merged as I'll have to update the execution tracking usage on various jackal / fission services, since this change breaks the older usage

(Necessary since we can't rely on storing this in the payload)

**Comment by ghost** [comment]
Fixing something... will reopen in a bit

**Comment by chrisroberts** [comment]
I don't know that we want to track specific executions within a callback, since in almost all cases the only publicly called methods will be `#valid?` and `#execute`.  The re-defining of the methods will need to be cleaned up as well so we can ensure it is only in use when required.

**Comment by ckuttruff** [comment]
closing for the time being since we just care about `execute` method as a public interface

**Comment by ghost** [comment]
closing for the time being since we just care about execute method as a public interface

**Pull request closed without merging**
